version: "3.1"
services:
  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - ./data/mysql:/var/lib/mysql
  admin:
    image: adminer
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:8080
